kind: ConfigMap
apiVersion: v1
metadata:
  name: gps-tracker-api-config
  namespace: prod
data:
  NODE_ENV: "gps-tracker"
  HOST: "0.0.0.0"
  PORT: "31111"
  BASE_PATH: "/api"
  LOG_TCP_DEBUG: "1"
  LOG_NON_GPS: "1"
  LOG_RAW: "1"
